services:
  mongodb-container:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ../mock-database-image-similarity/mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGOODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}

  mongoexpress-container:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGOEXPRESS_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGOEXPRESS_ADMINPASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGOODB_USERNAME}:${MONGODB_PASSWORD}@mongodb-container:27017/
      - ME_CONFIG_BASICAUTH=true
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_ADMINUSERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_ADMINPASSWORD}

volumes:
  mongodb-container:
