services:
  rabbitmq-container:
    image: rabbitmq:management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - rabbitmq_streamlit_net

networks:
  rabbitmq_streamlit_net:
    driver: bridge

volumes:
  rabbitmq_data:
  rabbitmq_log:
